### ISSUE TITLE
Compilation warning with Elixir 1.8.1

### ISSUE THREAD

**Issue by denispeplin** [Schultzer/unidekode#1]
```elixir
==> unidekode
Compiling 1 file (.ex)
warning: the Collectable protocol is deprecated for non-empty lists. The behaviour of things like Enum.into/2 or "for" comprehensions with an :into option is incorrect when collecting into non-empty lists. If you're collecting into a non-empty keyword list, consider using Keyword.merge/2 instead. If you're collecting into a non-empty list, consider concatenating the two lists with the ++ operator.
  (elixir) lib/collectable.ex:83: Collectable.List.into/1
  (elixir) lib/enum.ex:1227: Enum.into_protocol/2
  lib/unidekode.ex:46: (module)
  (elixir) src/elixir_compiler.erl:79: :elixir_compiler.dispatch/4
  (elixir) src/elixir_compiler.erl:63: :elixir_compiler.compile/3
```

**Comment by Schultzer** [comment]
Thanks @denispeplin. I've released a new version on hex.

**Comment by denispeplin** [comment]
Thanks!
